name: Mapped deployment
on:
# workflow_dispatch: {}
  push: {}
jobs:
  authenticate:
    name: AWS Authentication
    runs-on: ubuntu-20.04
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.BUILD_NRW_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.BUILD_NRW_AWS_SECRET_ACCESS_KEY }}
        aws-region: "${{ steps.mapper.outputs.region }}"
    - name: "Login to Amazon ECR"
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1   

  publish:
    name: ECR Image Upload
    needs: authenticate
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "Check for mapped deployment"
      id: mapper
      uses: epimorphics/deployment-mapper@1.2
      with:
        ref: "${{github.ref}}"
    - name: "Create ECR"
      uses: epimorphics/github-actions/create-ecr-action@0.6
      with:
        image: ${{ steps.mapper.outputs.image }}
    - name: "Get Git Tag"
      id: gitinfo
      uses: epimorphics/github-actions/git-info@0.6
    - name: "Publish image"
      env:
        ACCOUNT: ${{ secrets.BUILD_NRW_AWS_ACCESS_KEY_ID }}
        IMAGE: ${{ steps.mapper.outputs.image }}
        TAG: ${{ steps.gitinfo.outputs.tag }}
      run:  make image publish
      shell: bash

  deploy:
    needs: publish
    steps:
    - name: ansible-deployment
      uses: actions/checkout@v2
      with:
        repository: epimorphics/nrw-ansible-deployment
        ref: main
        path: nrw-ansible-deployment
        token: "${{ secrets.GIT_REPOSITORY_FULL_ACCESS_PAT }}"
