name: Mapped deployment
on:
# workflow_dispatch: {}
  push: {}
jobs:
  Deploy:
    env:
      ANSIBLE_REPO: nrw-ansible-deployment
      ANSIBLE_TAG: aws,widgets_cicd
      AWS_ACCESS_KEY_ID: "${{ secrets.BUILD_NRW_AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.BUILD_NRW_AWS_SECRET_ACCESS_KEY }}"
      AWS_REGION: "eu_west_1"
      HOST_PREFIX: "nrw"
      SSH_KEY: "${{ secrets.NRW_SSH_KEY }}"

    #---- Below this line should not require editing ----

    name: "ECR Image Upload and Ansible Deployment"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        path: build

    - name: "Check for mapped deployment"
      id: mapper
      uses: epimorphics/yml2image@0.04
      with:
        ref: "${{github.ref}}"
        mapFile: build/map.yml

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: "${{ env.AWS_ACCESS_KEY_ID }}"
        aws-secret-access-key: "${{ env.AWS_SECRET_ACCESS_KEY }}"
        aws-region: "${{ env.AWS_REGION }}"

    - name: "Login to Amazon ECR"
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1   

    - name: "Create ECR"
      uses: epimorphics/github-actions/create-ecr-action@1.55
      with:
        image: ${{ steps.mapper.outputs.image }}

    - name: "Get git tag"
      id: gitinfo
      uses: epimorphics/github-actions/git-info@1.55
      with:
        path: build

    - name: "Publish image"
      env:
        IMAGE: ${{ steps.mapper.outputs.image }}
        TAG: ${{ steps.gitinfo.outputs.tag }}
      run: |
        cd build
        make image publish
        cd ..
        rm -rf build
      shell: bash

    - name: SSH Setup
      uses: shimataro/ssh-key-action@v2
      with:
        key: "${{ env.SSH_KEY }}"
        known_hosts: unnesessary

    - name: Install Ansible
      uses: epimorphics/github-actions/ansible@1.55
      with:
        aws-access-key-id: "${{ env_AWS_ACCESS_KEY_ID }}"
        aws-secret-access-key: "${{ env_AWS_SECRET_ACCESS_KEY }}"
        aws-region: "${{ env.AWS_REGION }}"
        host-prefix: "${{ env.HOST_PREFIX}}"

    - name: Ansible Deployment Repository Checkout
      id: deploy
      uses: actions/checkout@v2
      with:
        repository: "epimorphics/${{ env.ANSIBLE_REPO }}"
        ref: "main"
        token: "${{ secrets.GIT_REPOSITORY_FULL_ACCESS_PAT }}"

    - name: Ansible Deploy
      uses: epimorphics/github-actions/ansible-deploy-tag@1.55
      with:
        repo: "${{ env.ANSIBLE_REPO }}"
        secret: "${{ secrets.ANSIBLE_VAULT_PASSWORD }}"
        stage: "${{ steps.gitinfo.outputs.target }}"
        tag: "${{ env.ANSIBLE_TAG }}"

