name: Ansible Deployment
on:
  workflow_dispatch: {}
  push: {}
env:
  ANSIBLE_REPO: epimorphics/nrw-ansible-deployment
  ANSIBLE_TAG: amptest
  AWS_ACCESS_KEY_ID: "${{ secrets.BUILD_NRW_AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.BUILD_NRW_AWS_SECRET_ACCESS_KEY }}"
  AWS_REGION: "eu-west-1"
  HOST_PREFIX: "nrw"
  SSH_KEY: "${{ secrets.NRW_SSH_KEY }}"

#---- Below this line should not require editing ----
jobs:
  setup:
    name: "Environment Setup"
    runs-on: ubuntu-20.04
    outputs:
      image: ${{ steps.mapper.outputs.image }}
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: "${{ env.AWS_ACCESS_KEY_ID }}"
        aws-secret-access-key: "${{ env.AWS_SECRET_ACCESS_KEY }}"
        aws-region: "${{ env.AWS_REGION }}"

    - name: "SSH Setup: github -> aws"
      uses: shimataro/ssh-key-action@v2
      with:
        key: "${{ env.SSH_KEY }}"
        known_hosts: unnesessary

    - name: "Install Ansible"
      uses: epimorphics/github-actions/ansible@v2
      with:
        aws-access-key-id: "${{ env.AWS_ACCESS_KEY_ID }}"
        aws-secret-access-key: "${{ env.AWS_SECRET_ACCESS_KEY }}"
        aws-region: "${{ env.AWS_REGION }}"
        host-prefix: "${{ env.HOST_PREFIX}}"

    - uses: actions/checkout@v2
      with:
        path: build

    - name: "Check for mapped deployment"
      id: mapper
      uses: epimorphics/github-actions/mapper@v2
      with:
        ref: "${{github.ref}}"
        mapFile: build/map.yml


  publish:
    needs: setup
    name: "ECR Image Upload"
    runs-on: ubuntu-20.04
    if: needs.setup.outputs.image != ''
    outputs:
      tag: ${{ steps.gitinfo.outputs.tag }}
    steps:
    - name: "Login to Amazon ECR"
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1   

    - name: debug
      shell: bash
      run: |
        echo "image: ${{ needs.setup.outputs.image }}"

    - name: "Create ECR"
      uses: epimorphics/github-actions/create-ecr-action@v2
      with:
        image: ${{ needs.setup.outputs.image }}

    - name: "Get git tag"
      id: gitinfo
      uses: epimorphics/github-actions/git-info@v2
      with:
        path: build

    - name: "Publish image"
      env:
        IMAGE: ${{ steps.setup.outputs.image }}
        TAG: ${{ steps.gitinfo.outputs.tag }}
      run: |
        cd build
        make image publish
        cd ..
        rm -rf build
      shell: bash


  deploy:
    needs: publish
    name: "Ansible Deploy"
    runs-on: ubuntu-20.04
    if: needs.publish.outputs.tag != ''
    steps:
    - name: "Ansible Deployment Repository Checkout"
      id: deploy
      uses: actions/checkout@v2
      with:
        repository: "${{ env.ANSIBLE_REPO }}"
        ref: "main"
        token: "${{ secrets.GIT_REPOSITORY_FULL_ACCESS_PAT }}"

    - name: "Ansible Deploy"
      uses: epimorphics/github-actions/ansible-deploy-tag@v2
      with:
        secret: "${{ secrets.ANSIBLE_VAULT_PASSWORD }}"
        stage: "${{ steps.mapper.outputs.target }}"
        name: "${{ env.ANSIBLE_TAG }}"
        version: "${{ steps.gitinfo.outputs.tag }}"

    - name: "Git Commit"
      shell: bash
      run: |
        git config --global user.name "Github CICD"
        git config --global user.email "noreply@epimorphics.com"
        git commit -am "Github/CICD: ${{ env.ANSIBLE_TAG }}:${{ needs.publish.outputs.tag }}"
        git push
