name: Mapped deployment
on:
# workflow_dispatch: {}
  push: {}
jobs:

  publish:
    name: ECR Image Upload
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: "Check for mapped deployment"
      id: mapper
      uses: epimorphics/deployment-mapper@1.2
      with:
        ref: "${{github.ref}}"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.BUILD_NRW_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.BUILD_NRW_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: "Login to Amazon ECR"
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1   

    - name: "Create ECR"
      uses: epimorphics/github-actions/create-ecr-action@1.04
      with:
        image: ${{ steps.mapper.outputs.image }}

    - name: "Get Git Tag"
      id: gitinfo
      uses: epimorphics/github-actions/git-info@1.04

    - name: "Publish image"
      env:
        IMAGE: ${{ steps.mapper.outputs.image }}
        TAG: ${{ steps.gitinfo.outputs.tag }}
      run:  make image publish
      shell: bash


  deploy:
    needs: publish
    name: Ansible Deployment
    runs-on: ubuntu-20.04
    steps:

    - name: Install Ansible
      uses: epimorphics/github-actions/ansible@1.06
      with:
        aws-profile: nrw
        aws-access-key-id: ${{ secrets.BUILD_NRW_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.BUILD_NRW_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu_west_1
        host-prefix: nrw
        ssh-key: ${{ secrets.NRW_SSH_KEY }}

    - name: Ansible deployment checkout
      uses: actions/checkout@v2
      with:
        repository: epimorphics/nrw-ansible-deployment
        ref: main
        path: nrw-ansible-deployment
        token: "${{ secrets.GIT_REPOSITORY_FULL_ACCESS_PAT }}"

    - name: Ansible Vault Secret
      shell: bash
      run: | 
        mkdir nrw-ansible-deployment/ansible/.secret && echo ${{ secrets.ANSIBLE_VAULT_PASSWORD }} > nrw-ansible-deployment/ansible/.secret/default

    - name: Deploy via Ansible
      shell: bash
      run: | 
        cd nrw-ansible-deployment/ansible && AWS_PROFILE=nrw ./eu-west-1/ec2.py --list
#       cd nrw-ansible-deployment/ansible && ansible -m setup monitor


