name: Mapped deployment
on:
  push: {}
jobs:
  publish:
    name: mapped-deployment
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "Check for mapped deployment"
      id: mapper
      uses: epimorphics/deployment-mapper@1.2
      with:
        ref: "${{github.ref}}"
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.BUILD_NRW_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.BUILD_NRW_AWS_SECRET_ACCESS_KEY }}
        aws-region: "${{ steps.mapper.outputs.region }}"
    - name: "Login to Amazon ECR"
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1   
    - name: "Create ECR"
      uses: epimorphics/create-ecr-action@0.1
      with:
        image: ${{ steps.mapper.outputs.image }}
    - name: "Publish image"
      if: steps.mapper.outputs.image != ''
      run: ACCOUNT=${{ secrets.BUILD_NRW_AWS_ACCESS_KEY_ID }} IMAGE=${{ steps.mapper.outputs.image }} TAG=${{ }} make image publish
      shell: bash
    - name: ansible-deployment
      uses: actions/checkout@v2
      with:
        repository: epimorphics/nrw-ansible-deployment
        ref: main
        path: nrw-ansible-deployment
        token: "${{ secrets.GIT_REPOSITORY_FULL_ACCESS_PAT }}"
