name: Mapped deployment
on:
# workflow_dispatch: {}
  push: {}
jobs:
  Deploy:
    env:
      ANSIBLE_REPO: nrw-ansible-deployment
      HOST_PREFIX: nrw

    name: "ECR Image Upload and Ansible Deployment"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        path: build

    - name: "Check for mapped deployment"
      id: mapper
      uses: epimorphics/yml2image@0.03
      with:
        ref: "${{github.ref}}"
        mapFile: build/map.yml

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.BUILD_NRW_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.BUILD_NRW_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: "Login to Amazon ECR"
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1   

    - name: "Create ECR"
      uses: epimorphics/github-actions/create-ecr-action@1.11
      with:
        image: ${{ steps.mapper.outputs.image }}

    - name: "Get git tag"
      id: gitinfo
      uses: epimorphics/github-actions/git-info@1.55
      with:
        path: build

    - name: "Publish image"
      env:
        IMAGE: ${{ steps.mapper.outputs.image }}
        TAG: ${{ steps.gitinfo.outputs.tag }}
      run: |
        cd build
        make image publish
        cd ..
        rm -rf build
      shell: bash

    - name: SSH Setup
      uses: shimataro/ssh-key-action@v2
      with:
        key: "${{ secrets.NRW_SSH_KEY }}"
        known_hosts: unnesessary

    - name: Install Ansible
      uses: epimorphics/github-actions/ansible@1.55
      with:
        aws-access-key-id: "${{ secrets.BUILD_NRW_AWS_ACCESS_KEY_ID }}"
        aws-secret-access-key: "${{ secrets.BUILD_NRW_AWS_SECRET_ACCESS_KEY }}"
        aws-profile: "nrw"
        aws-region: "eu_west_1"
        host-prefix: "${{ env.HOST_PREFIX}}"

    - name: Ansible Deployment Repository Checkout
      id: deploy
      uses: actions/checkout@v2
      with:
        repository: "epimorphics/${{ env.ANSIBLE_REPO }}"
        ref: "main"
        token: "${{ secrets.GIT_REPOSITORY_FULL_ACCESS_PAT }}"

    - name: DEBUG
      shell: bash
      run: |
        pwd
        ls -la
        cd ..
        pwd
        ls -la

    - name: Ansible Deploy
      uses: epimorphics/github-actions/ansible-deploy-tag@1.55
      with:
        aws-profile: "nrw"
        repo: "${{ env.ANSIBLE_REPO }}"
        secret: "${{ secrets.ANSIBLE_VAULT_PASSWORD }}"
        stage: "dev"
        tag: "widgets"

