name: Mapped deployment
on:
# workflow_dispatch: {}
  push: {}
jobs:
  publish:
    name: "ECR Image Upload"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: "Check for mapped deployment"
      id: mapper
      uses: epimorphics/deployment-mapper@1.2
      with:
        ref: "${{github.ref}}"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.BUILD_NRW_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.BUILD_NRW_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: "Login to Amazon ECR"
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1   

    - name: "Create ECR"
      uses: epimorphics/github-actions/create-ecr-action@1.11
      with:
        image: ${{ steps.mapper.outputs.image }}

    - name: "Get git tag"
      id: gitinfo
      uses: epimorphics/github-actions/git-info@1.11

    - name: "Publish image"
      env:
        IMAGE: ${{ steps.mapper.outputs.image }}
        TAG: ${{ steps.gitinfo.outputs.tag }}
      run:  make image publish
      shell: bash

    - name: "Cleanup workspace"
      run: |
        pwd
        ls -la
      shell: bash


  deploy:
    needs: publish
    name: Ansible Deployment
    runs-on: ubuntu-20.04

    env:
      ANSIBLE_REPO: nrw-ansible-deployment
      HOST_PREFIX: nrw

    steps:
    - name: Install Ansible
      uses: epimorphics/github-actions/ansible@1.26

    - name: Ansible Deployment Repository Checkout
      uses: actions/checkout@v2
      with:
        repository: "epimorphics/${{ env.ANSIBLE_REPO }}"
        ref: "main"
        token: "${{ secrets.GIT_REPOSITORY_FULL_ACCESS_PAT }}"

    - name: Ansible Deploy
      uses: epimorphics/github-actions/ansible-deploy-tag@1.28
      with:
        aws-access-key-id: "${{ secrets.BUILD_NRW_AWS_ACCESS_KEY_ID }}"
        aws-secret-access-key: "${{ secrets.BUILD_NRW_AWS_SECRET_ACCESS_KEY }}"
        aws-region: "eu_west_1"
        host-prefix: "${{ env.HOST_PREFIX}}"
        repo: "${{ env.ANSIBLE_REPO }}"
        secret: "${{ secrets.ANSIBLE_VAULT_PASSWORD }}"
        ssh-key: "${{ secrets.NRW_SSH_KEY }}"
        stage: "dev"
        tag: "widgets"
